apiVersion: v2
name: farts
description: Flying Animal Recon Telecommunication Service for a BirdWeather station.
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/TheOutdoorProgrammer/farts
sources:
  - https://github.com/TheOutdoorProgrammer/farts
